### PR TITLE
switch commands to argparse

### PR DESCRIPTION
**Pull request by davidszotten**
use argparse for django 1.8+ to avoid deprecation warnings

### CODE REVIEW

**Comment by spookylukey** [comment]
Excellent, thanks so much.

**Comment by davidszotten** [comment]
cool. any chance of a new release?

**Comment by spookylukey** [comment]
@ossanna16 - do you have any input on when releases of django-mailer should be made?

**Comment by ossanna16** [comment]
@spookylukey I don't but @paltman or @jtauber may :)

**Comment by davidszotten** [comment]
bump?

**Comment by ossanna16** [comment]
Pinging @jtauber @paltman and @spookylukey :)

**Comment by spookylukey** [comment]
With no comment from @jtauber or @paltman I'm assuming it's OK to release, and will do so shortly.

**Comment by spookylukey** [comment]
Done: https://pypi.python.org/pypi/django-mailer

**Comment by ossanna16** [comment]
Thanks @spookylukey!

**Comment by davidszotten** [comment]
thank you!

**Pull request merged**
