### PR TITLE
Add psycopg3 support to runmailer_pg

### PR DESCRIPTION
**Pull request by jsmits**
Changes proposed in this PR:

- Add psycopg3 support to runmailer_pg and gracefully exit on SIGINT

**Tips for an ideal PR**
* You have read our Code of Conduct: https://github.com/pinax/.github/blob/master/CODE_OF_CONDUCT.md
* You have read our Contributing info: https://github.com/pinax/.github/blob/master/CONTRIBUTING.md
* The PR is atomic
* Unit tests have been updated/added, if needed
* App version number has been updated in `setup.py` (Pinax uses [SemVer](https://semver.org/))
* `Change Log` has been updated
* You have added your name to the `AUTHORS` file

### CODE REVIEW

**Comment by spookylukey** [comment]
Hi @jsmits thanks for the PR.

Could you give me some context and a high level description about what is going on here? Thanks!

**Comment by jsmits** [comment]
> Hi @jsmits thanks for the PR.
> 
> Could you give me some context and a high level description about what is going on here? Thanks!

Sure, no problem. I tried to run the runmailer_pg in my latest django project and it crashed because it uses psycopg3. It expects psycopg2 still. This PR makes it seamlessly run with both, so if you have psycopg3 installed, it will use that, and if you have pscyopg2 installed, it will just, like it before. Probably more people will start running into this if they start using django with psycopg3 and django-mailer’s runmailer_pg.

**Comment by jsmits** [comment]
> Can you explain why this isn't just case of changing imports? Specifically what is different in psycopg3 that requires changes? Thanks!

Basically two things:
- connection.poll() is not there anymore in psycopg3; instead you can consume its connection.notifies() generator, which I did
- psycopg3 does the autocommit part differently, the way psycopg2 did it doesn’t work anymore for psycopg3

**Comment by jsmits** [comment]
Awesome, thanks a lot!

**Pull request merged**
