### PR TITLE
management command for cleaning up old records

### PR DESCRIPTION
**Pull request by grzn**

### CODE REVIEW

**Comment by spookylukey** [comment]
This would need docs and tests before it could be merged. Also the flake8 failures would need to be fixed. Thanks!

**Comment by grzn** [comment]
Now that I know you're okay with the idea, I'll make the adjustments this
weekend.

Thanks

-- 
Guy Rozendorn

**Comment by spookylukey** [comment]
OK. While you are there, it would also need to include good docs when you do `./manage.py clean_mail_log`, and actually I think that command should sound more dangerous e.g. `purge_mail_logs`.

**Comment by grzn** [comment]
Added documentation and made all the tests pass.

**Comment by ossanna16** [comment]
@spookylukey Is this ready to be merged? :)

**Comment by grzn** [comment]
Yes
-- 
Guy Rozendorn

**Comment by ossanna16** [comment]
@grzn I'll let @spookylukey merge this. Thanks a ton for your work!

**Comment by spookylukey** [comment]
Thanks, merged now. FYI, I did some cleanups in 9dfde938900131da93cc1307f1323ac45f79abd6 and 295a08f3eaae67e3bf29a8b9a65c5c55875d3fe8

**Comment by ossanna16** [comment]
Thanks @spookylukey!

**Pull request merged**
