### PR TITLE
django 2.0 compat

### PR DESCRIPTION
**Pull request by davidszotten**
django < 2.0 is fine inserting bytestrings into a textfield, but as of 2.0 there is a (py3) `isinstance(str)` -> `str(value)` which for `b'foo'` becomes `"b'foo'"`

### CODE REVIEW

**Comment by davidszotten** [comment]
ping @spookylukey

**Comment by spookylukey** [comment]
Thanks!

**Comment by davidszotten** [comment]
thank you! any chance of a release? anything i can do to make that easier (e.g. do you like/dislike changes.txt + version bumps in the same pr)?

**Comment by spookylukey** [comment]
An entry in CHANGES.txt would help. Normally I follow RELEASE.rst but it looks like I forgot to add the new section.

**Pull request merged**
