### PR TITLE
Added the ability to search email body in admin.

### PR DESCRIPTION
**Pull request by benkonrath**
This seems to be working but I'm not sure if there will be performance issues with a large number of email messages. Any thoughts?

### CODE REVIEW

**Comment by spookylukey** [comment]
I don't see how this can work. For it to work, you would need the following to be true:

x in y => base64_encode(x) in base64_encode(y)

However, it is easy to find counter examples that show this is not true:

    >>> base64_encode('1')
    'MQ==\n'
    >>> base64_encode('1a')
     'MWE=\n'
    >>> base64_encode('a1')
     'YTE=\n'

In other words, The encoding for '1' is 'MQ', which is not found in the encoding for '1a' or 'a1'. This is what I would expect from the way that [Base64](https://en.wikipedia.org/wiki/Base64) encodes 3 bytes by treating them as 24 bits then splitting into 4 groups of 6 bits and encoding as 4 bytes. This means that it will only sometimes work, depending on the alignment of the bytes:

    >>> base64_encode('abc').strip('\n') in base64_encode('abcdefghi')
    True

    >>> base64_encode('bcd').strip('\n') in base64_encode('abcdefghi')
    False

As well as false negatives, I think you will also get false positives, though it's harder to come up with examples.

Did I miss something?

**Comment by benkonrath** [comment]
No, you didn't miss anything. This was a bit of a naive implementation because I didn't investigate base64 properly. I just tested one string that happened to work but as you've pointed out, this isn't always going to work and can produce false positives. 

I did quick search to see if there as a solution for searching base64 data without decoding. I found this solution but the string needs to be long enough for it to work.
http://stackoverflow.com/a/347296/1636882

I'm closing this issue because I don't think this is a reasonable solution for this use case.

**Comment by benkonrath** [comment]
I forgot to mention: This came about because an admin user reported that they couldn't search through the message log. I was also confused that searching for email text didn't work with the search field. I now understand why this isn't possible to implement (at least in all cases). It would be nice if the search functionality clearly stated somewhere in the UI that it's only for searching the message ids.

**Comment by spookylukey** [comment]
Definitely it would be good to make the UI clear. At the moment you'd have to read the source code!

The only easy possibility I can think of for searching the body is if we were to extract the body as plain text in a separate field. While I can see the usefulness, I'm reluctant to do that, however - the app is advertised as essentially being a mail queue, and anything else we can implement in top is a bonus, and adding the body in plain text could approximately double storage in some cases.

**Comment by benkonrath** [comment]
I agree that extracting the email body into a new field isn't a good option as well because of the extra storage space required as you point out. I'll see if I can come up with a simple solution for make the UI more clear.

**Comment by hellvix** [comment]
There is no way we can search for e-mail addresses then?

**Comment by spookylukey** [comment]
@hellvix - recipients etc. are stored as part of the pickled message data, not as separate fields, so can't be searched.

**Pull request closed without merging**
