### PR TITLE
Retry limit

### PR DESCRIPTION
**Pull request by jaap3**
Closes # 161.

Changes proposed in this PR:

- Add setting to limit the amount of retries for deferred messages

### CODE REVIEW

**Comment by jaap3** [comment]
@spookylukey Is support for Python 2.7 (in tests) still required? Same with Python < 3.7, these versions don't seem to be available in GitHub actions ([support has ended for these versions](https://endoflife.date/python)).

**Comment by spookylukey** [comment]
Yes, we can drop support for Python 2.7 and Python 3.5, 3.6

**Comment by jaap3** [comment]
@spookylukey See https://github.com/pinax/django-mailer/pull/166, I can rebase this PR once that one is accepted/merged

**Comment by jaap3** [comment]
@spookylukey hope you can find some time to look at this 🙏

**Comment by spookylukey** [comment]
This looks good to me, thanks!

**Pull request merged**
