### PR TITLE
catch errors when sending email via the Amazon SES API

### PR DESCRIPTION
**Pull request by taleinat**
This is required when using `django-mailer` in conjunction with `django-ses`.

### CODE REVIEW

**Comment by spookylukey** [comment]
Thanks so much for this. It looks like this overlaps quite significantly with PR #78 (see also issue #73). It would be *really* helpful if you could look at that PR and see if it would solve your issue.

I want to avoid putting any exception handling specific to certain email providers, as there is no end to the things we'd need to add.  (Yes, we already have SMTP, but can't really avoid that now).

Thanks!

**Comment by taleinat** [comment]
I read both of those. The discussion seems positive and in the right direction, but this has been open since November 2016, i.e. for about eight months. This is a small, straightforward change that adds support for a very common email sending service. In my opinion it is better not to wait for the highly generic re-engineered solution when there is a reasonable straightforward implementation available.

Specifically in my case, it means I need to maintain a fork of this project just for this support, which I'd prefer to avoid. It also complicates my dependency handling, since I can't just add `django-mailer` to `requirements.txt` and be done with it.

I'll try to find time to look at PR #78, but I can't promise anything.

**Comment by spookylukey** [comment]
I think #78 is nearly there, and may even be ready for merge.

There are backwards compatibility issues here around error handling. There is absolutely no point adding a feature/fix as in this PR just to have a regression due to a different approach being taken.

Regarding requirements.txt, you can indeed use your branch directly until this package is fixed - see https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source#16584935

**Comment by taleinat** [comment]
Then go with #78. With it, we'd still delete any failed email message sent via SES rather than retrying it, which isn't what I'd expect or want. It would be easy to add SES-specific errors to the list of those leading to deferring (rather than deleting) of messages, though.

**Comment by spookylukey** [comment]
Closed in favour of #133. Thanks for your patience - this took lots of work on dead ends and refining different approaches.

**Pull request closed without merging**
