### PR TITLE
Protect against email backend loop (fixes #108)

### LINKED ISSUE #108: Protect against loop from EMAIL_BACKEND equal to MAILER_EMAIL_BACKEND?
Hi!

I had a situation where `MAILER_EMAIL_BACKEND` and `EMAIL_BACKEND` were both set to `mailer.backend.DbBackend` (with version 1.2.4). The symptom is that sending mails does not seem to work, until you notice that there is new rows in the database.

I was wondering if that's a scenario you consider worth protecting against. What do you think?

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Meant to address #108

### CODE REVIEW

**Comment by hartwork** [comment]
CI is happy now, let me know what you think :smiley:

**Comment by spookylukey** [comment]
On reviewing your patch (thank you!) I realized that there is a valid case for `EMAIL_BACKEND == MAILER_EMAIL_BACKEND`. For example, you could set them both to the default `django.core.mail.backends.smtp.EmailBackend`. In this case, you wouldn't be using django-mailer  as a backend, but you can still import its `send_mail` function directly and use that. In fact, this is how django-mailer originally worked, before Django gained a configurable `EMAIL_BACKEND` setting.

So, the case we actually need to catch is when `MAILER_EMAIL_BACKEND` is set to "mailer.backend.DbBackend". Sorry for not thinking of that sooner!

**Comment by hartwork** [comment]
I see! The could be yet another proxy backend in front of django-mailer so I have made the check deny only `MAILER_EMAIL_BACKEND == EMAIL_BACKEND == 'mailer.backend.DbBackend'`. Still better than noting in my book and should not stand in the way of creative use either. Let me know what you think.

**Comment by hartwork** [comment]
Good to merge?

**Comment by spookylukey** [comment]
Thanks @hartwork !

**Pull request merged**
