### PR TITLE
Support alive versions of Python and Django

### PR DESCRIPTION
**Pull request by hartwork**
@spookylukey could you have a look?

### CODE REVIEW

**Comment by spookylukey** [comment]
Is there a particular need to drop the older versions?

My own experience is that it can really help people to upgrade when dependencies span as many versions as possible e.g. spanning 2 Django LTS versions can really help. To date django-mailer has been such a small library that the work of supporting old Python and Django versions has been very small.

But if supporting old versions is causing significant issues we can drop them.

**Comment by hartwork** [comment]
> Is there a particular need to drop the older versions?

We're doing two things here: Adding new and dropping old.
The reason for dropping is:
- Ability to simplify code by dropping crutches needed to support old version
- Reducing maintenance cost of older versions to zero for humans and CI. There is no support for something without _someone_ paying a price and this way it's not the community. If some company wants to run say django-mailer with Python 2.7 then they pay, not the community. It think that's fair.

> My own experience is that it can really help people to upgrade when dependencies span as many versions as possible e.g. spanning 2 Django LTS versions can really help.

I agree with regard to LTS versions that are _not_ end-of-life. This pull request only drops things that are 100% dead upstream as of today.

> To date django-mailer has been such a small library that the work of supporting old Python and Django versions has been very small.

Small but not zero and ongoing and hence adding up. Paid by volunteers.

**Comment by spookylukey** [comment]
> If some company wants to run say django-mailer with Python 2.7 it's on them, not the community. It think that's fair.

The person running django-mailer on older versions of Python/Django could also be an overworked Open Source contributor who is struggling to keep all their projects updated. In my experience when you have libraries that support a large range of dependencies, especially spanning multiple LTS versions at the same time, it gives significant flexibility with upgrades and makes life easier.

I would also consider any user to be part of the "community", or potentially so, even if they are a company that so far hasn't contributed. If we unnecessarily alienate people due to dropping support simply as fast as we can, we can actually push potential contributors away, and the remaining community also pays the cost for that.

In addition, there is also a maintenance cost to dropping support - for example, in documenting that you've dropped support, in checking upgrade paths etc. For example, I'm glad I don't have to write a compat table like the one on [django-wiki](https://github.com/django-wiki/django-wiki/). It actually can keep things simpler in some cases to not delay dropping support.

So that's why my normal method, for these very small libraries, is to drop support when it causes me a problem, and not before.

We can leave this PR open for when that time comes. Thanks :-)

**Comment by hartwork** [comment]
I don't consider that alienation, I consider it healthy. We can only agree to disagree then, I guess.

I think it's interesting to note that both you and I have invested time now only because of existing support for end-of-live versions of Django and Python in this project: We wouldn't even discuss here without it.  I think that proves my point as a side effect: There is no support without *someone* paying for it with their time, the only question is *who*.

**Comment by hartwork** [comment]
Closing due to arrival of conflicts and earlier rejection (see above).

**Pull request closed without merging**
