### PR TITLE
pin and save a message-id header

### PR DESCRIPTION
**Pull request by davidszotten**
For discussion in #57

### CODE REVIEW

**Comment by ossanna16** [comment]
Thanks @davidszotten! @lukeman Can this be merged?

**Comment by davidszotten** [comment]
this is foremost to aid the discussion. i know you're not asking me, but i'm not convinced i like this change

**Comment by spookylukey** [comment]
@ossanna16 I think when you refer to @lukeman you are meaning me, @spookylukey . @lukeman has never been active on this project: https://github.com/pinax/django-mailer/graphs/contributors

I think this change looks good - what exactly is your reluctance @davidszotten ? In the other thread you said that django "throws away" the message id, but only in the sense that it throws the whole message away - it is persisted by the act of passing it on to the SMTP backend. In our case, django-mailer is acting as an intermediary backend, so it is quite appropriate for it to persist this value AFAICS (or set it if it is not set already).

A few tweaks I would suggest:
* some docs to make it discoverable
* changing the MessageLog admin to make the field searchable. This might make docs unnecessary actually, as it makes the feature discoverable.

**Comment by ossanna16** [comment]
@spookylukey I did mention the wrong Luke, you are right. I'm sorry! @jtauber just notified me about that today, too.

**Comment by davidszotten** [comment]
it just feels a bit ugly to hoist (duplicate) code out of the django smtp backend. ("throw away" in the sense that there isn't a way for a caller to get hold of it)

do we need to worry about potentially sending out emails with duplicate message ids? (e.g. if a message gets deferred due to a sending error and we retry)

good idea about making the field searchable

**Comment by spookylukey** [comment]
I guess it would be good to have a test that ensures that if a message is retried, it doesn't get a new Message-ID.

Other than that, I'm not worried about the duplication of setting a Message-ID - it's what mail sending services are supposed to do if there isn't a Message-ID already, so its perfectly legitimate for us to set it since django-mailer is a "mail sending backend" of a sort.

**Comment by davidszotten** [comment]
to be clear, i'm not worried about it _not_ getting set, i'm worried that by setting the header "too early" in the pipeline (before we enqueue email in our db), we might end up sending multiple emails with the same message-id. that seems to be against the spec, though i'm not sure if/what problems that might cause downstream

**Comment by spookylukey** [comment]
I don't think we are setting it too early. In fact, most end-user mail 
programs (Thunderbird etc.) set the Message-ID themselves, even at draft 
stage, which is conceptually "earlier" than we are doing. As long as you 
are not generating dupes (should be guaranteed by make_msgid) and are 
not overwriting the message id if it exists already (as in your patch), 
we should be good.

**Comment by davidszotten** [comment]
finally back from some travels and able to add to admin

**Comment by spookylukey** [comment]
This LGTM. I think it just needs something adding to CHANGES.rst. That will also probably require a new section adding, perhaps just "Development version", which we can adjust to the version when we know what it is.

**Comment by davidszotten** [comment]
wasn't quite sure how to phrase it but have added a sentence. thoughts on better wording welcome

**Comment by spookylukey** [comment]
Thanks, and thanks for putting up with my nit-picking!

**Comment by davidszotten** [comment]
Not at all, i know the feeling from the "other side" :) Thanks for helping me get this over the line!

**Pull request merged**
