### PR TITLE
Fix flake8 warnings; freeze flake version for tox.

### PR DESCRIPTION
**Pull request by medmunds**

### CODE REVIEW

**Comment by spookylukey** [comment]
Could you add the flake8 version you used into tox.ini so that we have a common target when running flake8 tests? Thanks.

**Comment by felixxm** [comment]
I also fixed this in #74. Errors appeared since flake8==3.2.0.

**Comment by medmunds** [comment]
(It looks like the change was introduced in pycodestyle 2.2.0 on 2016-11-04: "Require two blank lines after toplevel def, class.")

**Comment by spookylukey** [comment]
Thanks!

**Pull request merged**
